### ISSUE TITLE
Format of phone number in pop-up form

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/MyHomesIntel#1]
1. Remove the 'Format: 000-000-0000' line
2. Please have the telephone field auto-format the number. They should be able to enter digits and it automatically puts in the dashes.
3. It should do this on desktop and mobile

The user registered his address but couldn't complete the sign-up because the phone number input doesn't allow for—to be added, e.g., 615-397-3487. He was using an iPhone.

**Comment by codextiny** [comment]
Sure, we will update the input functionality to auto-format the number, it will require custom JS and take time.
One more thing need to confirm you are talking about this number field, please confirm.
![image](https://github.com/shannonbaldwin/MyHomesIntel/assets/113863175/f81a9c7a-8e82-485a-bf6a-59bb9a6f1d54)

@shannonbaldwin

**Comment by shannonbaldwin** [comment]
@codextiny Yes, this is correct. Please send estimate

**Comment by codextiny** [comment]
Hi @shannonbaldwin 
It's done from our side Please check.

**Comment by c313ste** [comment]
Still having auto-format issues. Please limit to ###-###-####


![](https://files.slack.com/files-pri/TCU1EHKU1-F0706PL5HND/image_from_ios.jpg)

**Comment by c313ste** [comment]
![image](https://github.com/shannonbaldwin/MyHomesIntel/assets/6625924/af61eabb-fafd-4d8c-a50f-2a267b203891)

**Comment by codextiny** [comment]
Hi @c313ste 

Can you please tell us on which iPhone and browser you are checking this?
Did you clear your browser cache or check in a private window or incognito mode?

Thanks

**Comment by c313ste** [comment]
Gotcha! Looks good. Thank you!
